language: php

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_install:
  - composer install --no-interaction

script: vendor/bin/phpunit --coverage-text

notifications:
  email: info@endroid.nl
